spring:
  application:
    name: eureka-client
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.129:8761/eureka/,http://192.168.80.129:8769/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30